// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FeedbackService.Domain.Models;

public partial class Driver
{
    public Guid DriverId { get; set; }

    public Guid UserId { get; set; }

    public string DriverLicense { get; set; }

    public Guid? SubscriptionPlanId { get; set; }

    public string SubscriptionStatus { get; set; }

    public DateOnly? SubscriptionStartDate { get; set; }

    public DateOnly? SubscriptionEndDate { get; set; }

    public int TotalSwaps { get; set; }

    public int LoyaltyPoints { get; set; }

    public virtual ICollection<StationReview> StationReviews { get; set; } = new List<StationReview>();

    public virtual ICollection<SupportTicket> SupportTickets { get; set; } = new List<SupportTicket>();

    public virtual ICollection<Swap> Swaps { get; set; } = new List<Swap>();
}