// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace FeedbackService.Domain.Models;

public partial class ev_battery_swapContext : DbContext
{
    public ev_battery_swapContext(DbContextOptions<ev_battery_swapContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Driver> Drivers { get; set; }

    public virtual DbSet<StationReview> StationReviews { get; set; }

    public virtual DbSet<SupportTicket> SupportTickets { get; set; }

    public virtual DbSet<Swap> Swaps { get; set; }
    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Driver>(entity =>
        {
            entity.HasKey(e => e.DriverId).HasName("pk_drivers");

            entity.ToTable("drivers");

            entity.HasIndex(e => e.UserId, "UQ__drivers__B9BE370EBF93FBE9").IsUnique();

            entity.HasIndex(e => new { e.SubscriptionPlanId, e.SubscriptionStatus }, "ix_drivers_subscription");

            entity.Property(e => e.DriverId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("driver_id");
            entity.Property(e => e.DriverLicense)
                .HasMaxLength(50)
                .HasColumnName("driver_license");
            entity.Property(e => e.LoyaltyPoints).HasColumnName("loyalty_points");
            entity.Property(e => e.SubscriptionEndDate).HasColumnName("subscription_end_date");
            entity.Property(e => e.SubscriptionPlanId).HasColumnName("subscription_plan_id");
            entity.Property(e => e.SubscriptionStartDate).HasColumnName("subscription_start_date");
            entity.Property(e => e.SubscriptionStatus)
                .HasMaxLength(20)
                .HasColumnName("subscription_status");
            entity.Property(e => e.TotalSwaps).HasColumnName("total_swaps");
            entity.Property(e => e.UserId).HasColumnName("user_id");
        });

        modelBuilder.Entity<StationReview>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("pk_station_reviews");

            entity.ToTable("station_reviews");

            entity.HasIndex(e => e.CreatedAt, "ix_station_reviews_created_at");

            entity.HasIndex(e => e.Rating, "ix_station_reviews_rating");

            entity.HasIndex(e => e.StationId, "ix_station_reviews_station");

            entity.Property(e => e.ReviewId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("review_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.DriverId).HasColumnName("driver_id");
            entity.Property(e => e.FacilityRating).HasColumnName("facility_rating");
            entity.Property(e => e.Rating).HasColumnName("rating");
            entity.Property(e => e.ReviewText).HasColumnName("review_text");
            entity.Property(e => e.ServiceSpeedRating).HasColumnName("service_speed_rating");
            entity.Property(e => e.StaffRating).HasColumnName("staff_rating");
            entity.Property(e => e.StationId).HasColumnName("station_id");
            entity.Property(e => e.SwapId).HasColumnName("swap_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Driver).WithMany(p => p.StationReviews)
                .HasForeignKey(d => d.DriverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_station_reviews_drivers");

            entity.HasOne(d => d.Swap).WithMany(p => p.StationReviews)
                .HasForeignKey(d => d.SwapId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("fk_station_reviews_swaps");
        });

        modelBuilder.Entity<SupportTicket>(entity =>
        {
            entity.HasKey(e => e.TicketId).HasName("pk_support_tickets");

            entity.ToTable("support_tickets");

            entity.HasIndex(e => e.CreatedAt, "ix_support_tickets_created_at");

            entity.HasIndex(e => e.DriverId, "ix_support_tickets_driver");

            entity.HasIndex(e => e.Priority, "ix_support_tickets_priority");

            entity.HasIndex(e => e.Status, "ix_support_tickets_status");

            entity.HasIndex(e => e.TicketNumber, "ux_support_tickets_number").IsUnique();

            entity.Property(e => e.TicketId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("ticket_id");
            entity.Property(e => e.AssignedTo).HasColumnName("assigned_to");
            entity.Property(e => e.Category)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("category");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.DriverId).HasColumnName("driver_id");
            entity.Property(e => e.Priority)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("medium")
                .HasColumnName("priority");
            entity.Property(e => e.ResolvedAt).HasColumnName("resolved_at");
            entity.Property(e => e.StationId).HasColumnName("station_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("open")
                .HasColumnName("status");
            entity.Property(e => e.Subject)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("subject");
            entity.Property(e => e.SwapId).HasColumnName("swap_id");
            entity.Property(e => e.TicketNumber)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("ticket_number");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Driver).WithMany(p => p.SupportTickets)
                .HasForeignKey(d => d.DriverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_support_tickets_drivers");

            entity.HasOne(d => d.Swap).WithMany(p => p.SupportTickets)
                .HasForeignKey(d => d.SwapId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("fk_support_tickets_swaps");
        });

        modelBuilder.Entity<Swap>(entity =>
        {
            entity.HasKey(e => e.SwapId).HasName("pk_swaps");

            entity.ToTable("swaps");

            entity.HasIndex(e => e.DriverId, "ix_swaps_driver");

            entity.HasIndex(e => e.StationId, "ix_swaps_station");

            entity.HasIndex(e => e.Status, "ix_swaps_status");

            entity.HasIndex(e => e.SwapStartTime, "ix_swaps_swap_time");

            entity.Property(e => e.SwapId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("swap_id");
            entity.Property(e => e.BatteryInChargeLevel).HasColumnName("battery_in_charge_level");
            entity.Property(e => e.BatteryInId).HasColumnName("battery_in_id");
            entity.Property(e => e.BatteryOutChargeLevel).HasColumnName("battery_out_charge_level");
            entity.Property(e => e.BatteryOutId).HasColumnName("battery_out_id");
            entity.Property(e => e.BookingId).HasColumnName("booking_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.DriverId).HasColumnName("driver_id");
            entity.Property(e => e.DurationMinutes).HasColumnName("duration_minutes");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.OdometerReading).HasColumnName("odometer_reading");
            entity.Property(e => e.StaffId).HasColumnName("staff_id");
            entity.Property(e => e.StationId).HasColumnName("station_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("in_progress")
                .HasColumnName("status");
            entity.Property(e => e.SwapEndTime).HasColumnName("swap_end_time");
            entity.Property(e => e.SwapStartTime)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("swap_start_time");
            entity.Property(e => e.VehicleId).HasColumnName("vehicle_id");

            entity.HasOne(d => d.Driver).WithMany(p => p.Swaps)
                .HasForeignKey(d => d.DriverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_swaps_drivers");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}