// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace FeedbackService.Domain.Models;

public partial class ev_battery_swapContext : DbContext
{
    public ev_battery_swapContext()
    {
    }

    public ev_battery_swapContext(DbContextOptions<ev_battery_swapContext> options)
        : base(options)
    {
    }

    public virtual DbSet<StationReview> StationReviews { get; set; }

    public virtual DbSet<SupportTicket> SupportTickets { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<StationReview>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("pk_station_reviews");

            entity.ToTable("station_reviews");

            entity.HasIndex(e => e.CreatedAt, "ix_station_reviews_created_at");

            entity.HasIndex(e => e.Rating, "ix_station_reviews_rating");

            entity.HasIndex(e => e.StationId, "ix_station_reviews_station");

            entity.Property(e => e.ReviewId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("review_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.DriverId).HasColumnName("driver_id");
            entity.Property(e => e.FacilityRating).HasColumnName("facility_rating");
            entity.Property(e => e.Rating).HasColumnName("rating");
            entity.Property(e => e.ReviewText).HasColumnName("review_text");
            entity.Property(e => e.ServiceSpeedRating).HasColumnName("service_speed_rating");
            entity.Property(e => e.StaffRating).HasColumnName("staff_rating");
            entity.Property(e => e.StationId).HasColumnName("station_id");
            entity.Property(e => e.SwapId).HasColumnName("swap_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<SupportTicket>(entity =>
        {
            entity.HasKey(e => e.TicketId).HasName("pk_support_tickets");

            entity.ToTable("support_tickets");

            entity.HasIndex(e => e.CreatedAt, "ix_support_tickets_created_at");

            entity.HasIndex(e => e.DriverId, "ix_support_tickets_driver");

            entity.HasIndex(e => e.Priority, "ix_support_tickets_priority");

            entity.HasIndex(e => e.Status, "ix_support_tickets_status");

            entity.HasIndex(e => e.TicketNumber, "ux_support_tickets_number").IsUnique();

            entity.Property(e => e.TicketId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("ticket_id");
            entity.Property(e => e.AssignedTo).HasColumnName("assigned_to");
            entity.Property(e => e.Category)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("category");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.DriverId).HasColumnName("driver_id");
            entity.Property(e => e.Priority)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("medium")
                .HasColumnName("priority");
            entity.Property(e => e.ResolvedAt).HasColumnName("resolved_at");
            entity.Property(e => e.StationId).HasColumnName("station_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("open")
                .HasColumnName("status");
            entity.Property(e => e.Subject)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("subject");
            entity.Property(e => e.SwapId).HasColumnName("swap_id");
            entity.Property(e => e.TicketNumber)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("ticket_number");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("updated_at");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}