// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FeedbackService.Domain.Models;

public partial class StationReview
{
    public Guid ReviewId { get; set; }

    public Guid DriverId { get; set; }

    public Guid StationId { get; set; }

    public Guid? SwapId { get; set; }

    public int Rating { get; set; }

    public string ReviewText { get; set; }

    public int? ServiceSpeedRating { get; set; }

    public int? StaffRating { get; set; }

    public int? FacilityRating { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Driver Driver { get; set; }

    public virtual Swap Swap { get; set; }
}