// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FeedbackService.Domain.Models;

public partial class SupportTicket
{
    public Guid TicketId { get; set; }

    public string TicketNumber { get; set; }

    public Guid DriverId { get; set; }

    public Guid? StationId { get; set; }

    public Guid? SwapId { get; set; }

    public string Category { get; set; }

    public string Priority { get; set; }

    public string Subject { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public Guid? AssignedTo { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? ResolvedAt { get; set; }
}